language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - cd ./bower_components/handlebars
  - npm install
  - grunt build
  - cd ../../
  - grunt build
script: grunt test --verbose --force
