language: node_js
node_js:
  - "4.1"
sudo: false
addons:
  sauce_connect:
    username: reboundjs
    access_key: 07875532-956f-448b-a77d-1520ac359f66
before_script:
  - "[[ $SUITE = saucelabs ]] && npm install -g saucie || true"
  - "[[ $SUITE = saucelabs ]] && npm install -g testem || true"
  - "npm run build"
env:
  - SUITE=phantomjs
  - SUITE=saucelabs
script: "[[ $SUITE = phantomjs ]] && npm test || testem ci"
